pipeline {
    agent any

    environment {
        APP_NAME = "recall-app"
        JAR_NAME = "recalling/target/*.jar"
        DEPLOY_DIR = "/var/lib/jenkins/app"
    }

    stages {
        stage('Clone') {
            steps {
                git branch: 'main' , url:'https://github.com/navidbasha/Recall.git'
            }
        }

        stage('Build') {
            steps {
                dir('recalling') {
                sh 'mvn clean package -DskipTests'
            }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    mkdir -p $DEPLOY_DIR
                    cp $JAR_NAME $DEPLOY_DIR/
                    pkill -f 'java.*.jar' || true
                    nohup java -jar $DEPLOY_DIR/*.jar > $DEPLOY_DIR/app.log 2>&1 &
                '''
            }
        }
    }
}
